version: '3'

services:

  payload:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - media:/home/node/app/media
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn build && yarn serve"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: development 
      PAYLOAD_SECRET: 3571b7a74da0ba4895e75f87 
      SERVER_URL: http://157.245.96.221

  mongo:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
  media:
